[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["pruebaapi"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "pruebaapi"
  org = "holamundowso2"
  version = "3.1.0"

